apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      enabled: false
      prune: true
      allowEmpty: true
      selfHeal: true
